"""empty message

Revision ID: 40626c0cb6d0
Revises: 
Create Date: 2022-04-08 12:17:35.617365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40626c0cb6d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('username', sa.String(length=15), nullable=True))
    op.create_unique_constraint(None, 'student', ['username'])
    op.alter_column('student', column_name='name', nullable=False, new_column_name='student_name')
    # op.drop_column('student', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_column('student', 'student_name')
    op.drop_column('student', 'username')
    # ### end Alembic commands ###
